[package]
name = "rsfetch"
version = "0.2.3"
edition = "2024"

[dependencies]
colored = "3.1.1"
font-kit = "0.14.3"
os-release = "0.1.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
directories = "6.0.0"
sysinfo = "0.37.2"
whoami = "2.0.2"
