[package]
name = "noorfetch"
version = "1.6.9"
edition = "2024"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true

[dependencies]
chrono = "0.4.43"
colored = "3.1.1"
os-release = "0.1.0"
sysinfo = "0.37.2"
whoami = "2.0.2"
